### ISSUE TITLE
Cannot send tweets with Turses 0.3.1

### ISSUE THREAD

**Issue by Hund** [dialelo/turses#211]
I'm using Arch linux with Turses 0.3.1 from AUR ([Link](https://aur.archlinux.org/packages/turses/)). Sending a tweet results in the error-message "Tweet not sent".

I have a debuglog. But its a lot of text and I'm not sure if contain any private information?

**Comment by shaggytwodope** [comment]
AUR package is broken and not sure what to do about it. The issue is the API was broke in tweepy. And turses is currently using an older version of it. But on arch(aur) the package is the newer one.

You can see the rollback of the depend here https://github.com/dialelo/turses/commit/dde099be534d891a79133e1ae15e84353ce99ea4

**Comment by Hund** [comment]
Ah. Thank you! I guess I have to wait a bit then. :)
